---
spring:
  profiles: default
  hateoas:
    use-hal-as-default-json-media-type: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
          lob:
            non_contextual_creation: true
  session:
    store-type: none
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/os_control?useTimezone=true&serverTimezone=America/Sao_Paulo
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    removeAbandoned: true
    validateQuery: SELECT 1
    remove-abandoned: true
    test-while-idle: true
    remove-abandoned-timeout: 900